import Image from "next/image";
import Link from "next/link";

export const metadata = {
  title: "Terms and Conditions — World Shift Technologies",
  description:
    "Terms governing your use of the World Shift Technologies website and tools.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col">

      {/* Nav */}
      <nav className="px-6 py-6 max-w-3xl mx-auto w-full">
        <Link href="/">
          <Image
            src="/World_shift_tech_LOGO_PRIMARY.png"
            alt="World Shift Technologies"
            width={180}
            height={45}
            className="object-contain"
            priority
          />
        </Link>
      </nav>

      {/* Content */}
      <main className="flex-1 max-w-3xl mx-auto w-full px-6 pb-20">
        <h1
          className="text-4xl font-light text-[#00205C] mb-3"
        >
          Terms and Conditions
        </h1>
        <p className="text-navy/70 text-sm mb-14">Last updated: June 8, 2026</p>

        <div className="space-y-10 text-[#00205C] text-base leading-[1.75]">

          <section>
            <h2 className="text-xs font-bold tracking-[0.2em] uppercase text-[#4B858E] mb-4">
              Acceptance of Terms
            </h2>
            <p>
              By accessing or using this website, you agree to be bound by these Terms and
              Conditions. If you do not agree, do not use the site.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-bold tracking-[0.2em] uppercase text-[#4B858E] mb-4">
              What This Site Is
            </h2>
            <p>
              This website is a consultation request and project scoping tool operated by World Shift
              Technologies, a Colorado-registered business. It is not a SaaS product and does not
              provide ongoing software access. Submitting a project request or completing an audit
              does not create a service agreement. Any engagement for services is governed by a
              separate written agreement executed between you and World Shift Technologies.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-bold tracking-[0.2em] uppercase text-[#4B858E] mb-4">
              AI-Generated Content
            </h2>
            <p>
              Portions of this site generate content using Anthropic&rsquo;s Claude AI model,
              including personalized landing pages, project scope documents, and AI waste audit
              reports. This content is produced algorithmically based on the information you provide
              and is for informational purposes only. It is not professional advice, a binding quote,
              a guarantee of outcomes, or a representation of what a formal engagement will cost or
              deliver. Actual scope, pricing, and results are confirmed in a separate written proposal.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-bold tracking-[0.2em] uppercase text-[#4B858E] mb-4">
              Scope and Pricing Estimates
            </h2>
            <p>
              Investment ranges generated by the project scoping wizard are starting estimates derived
              from your answers. They reflect typical ranges for the type of project described and do
              not account for factors that only become clear through a full discovery conversation.
              Final pricing is established in a written proposal following that conversation.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-bold tracking-[0.2em] uppercase text-[#4B858E] mb-4">
              Audit Reports
            </h2>
            <p>
              Waste estimates and ROI projections produced by the AI waste audit tool are illustrative
              estimates based on industry benchmarks and the tool information you provide. Actual
              savings depend on your specific implementation, team adoption, and existing processes.
              No specific outcome is guaranteed.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-bold tracking-[0.2em] uppercase text-[#4B858E] mb-4">
              Your Account
            </h2>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials and
              for all activity that occurs under your account. You agree to provide accurate
              information when creating an account and to notify us immediately of any unauthorized
              use at{" "}
              <a
                href="mailto:drew@worldshifttech.com"
                className="text-[#4B858E] hover:underline"
              >
                drew@worldshifttech.com
              </a>
              . One account per person.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-bold tracking-[0.2em] uppercase text-[#4B858E] mb-4">
              Acceptable Use
            </h2>
            <p>
              You agree not to scrape or systematically extract content from this site, submit false
              or misleading information through any form or wizard, impersonate any person or
              organization, or attempt to interfere with or compromise the security or integrity of
              the site.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-bold tracking-[0.2em] uppercase text-[#4B858E] mb-4">
              Intellectual Property
            </h2>
            <p>
              The content, design, code, and tools on this site are owned by World Shift Technologies
              and protected by applicable intellectual property laws. The information you submit
              through forms and wizards (your business descriptions, project ideas, and tool
              configurations) remains yours. By submitting it, you grant World Shift Technologies a
              limited license to process it for the purpose of generating your requested output.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-bold tracking-[0.2em] uppercase text-[#4B858E] mb-4">
              Limitation of Liability
            </h2>
            <p>
              To the fullest extent permitted by law, World Shift Technologies is not liable for any
              indirect, incidental, or consequential damages arising from your use of this site or
              reliance on AI-generated estimates, scope documents, or audit reports. The site is
              provided &ldquo;as is&rdquo; without warranties of any kind.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-bold tracking-[0.2em] uppercase text-[#4B858E] mb-4">
              Governing Law
            </h2>
            <p>
              These Terms are governed by the laws of the State of Colorado, without regard to its
              conflict of law provisions. Any disputes arising under these Terms will be resolved in
              the courts of Colorado.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-bold tracking-[0.2em] uppercase text-[#4B858E] mb-4">
              Changes to These Terms
            </h2>
            <p>
              We may update these Terms from time to time. The &ldquo;Last updated&rdquo; date at
              the top of this page reflects the most recent revision. Continued use of the site
              constitutes acceptance of the revised Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-bold tracking-[0.2em] uppercase text-[#4B858E] mb-4">
              Contact
            </h2>
            <p>
              World Shift Technologies —{" "}
              <a
                href="mailto:drew@worldshifttech.com"
                className="text-[#4B858E] hover:underline"
              >
                drew@worldshifttech.com
              </a>
            </p>
          </section>

        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-[#00205C]/[0.12] py-8 px-6">
        <div className="max-w-3xl mx-auto text-navy/70 text-sm">
          <p>&copy; {new Date().getFullYear()} World Shift Technologies</p>
        </div>
      </footer>

    </div>
  );
}
