import Image from "next/image";
import Link from "next/link";

export const metadata = {
  title: "Security & Data Privacy — World Shift Technologies",
  description:
    "How World Shift Technologies protects client files and project data, and why your information is never used to train AI models.",
};

export default function SecurityPage() {
  return (
    <div className="min-h-screen flex flex-col">

      {/* Nav */}
      <nav className="sticky top-0 z-40 w-full bg-white/90 backdrop-blur-sm border-b border-[#00205C]/10 shadow-sm">
        <div className="px-6 py-5 max-w-3xl mx-auto w-full">
          <Link href="/">
            <Image
              src="/World_shift_tech_LOGO_PRIMARY.png"
              alt="World Shift Technologies"
              width={180}
              height={45}
              className="object-contain"
              priority
            />
          </Link>
        </div>
      </nav>

      {/* Content */}
      <main className="flex-1 max-w-3xl mx-auto w-full px-6 pb-20">
        <h1 className="text-4xl font-light text-[#00205C] mb-3">
          Security & Data Privacy
        </h1>
        <p className="text-navy/70 text-sm mb-14">Last updated: August 13, 2026</p>

        <div className="space-y-10 text-[#00205C] text-base leading-[1.75]">

          <section>
            <p>
              Every project dashboard on this site carries client documents, project details, and
              business information that needs to stay private. This page explains exactly how that
              information is protected, in plain language, not compliance checklist language. If
              anything here is unclear or you want more detail before uploading something, email{" "}
              <a href="mailto:drew@worldshifttech.com" className="text-[#4B858E] hover:underline">
                drew@worldshifttech.com
              </a>{" "}
              and I&rsquo;ll walk you through it directly.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-bold tracking-[0.2em] uppercase text-[#4B858E] mb-4">
              Your Data Is Never Used to Train AI Models
            </h2>
            <p>
              Personalized pages, audit results, and project scoping on this site are generated by
              calling Anthropic&rsquo;s Claude API directly through a paid commercial account. Under
              Anthropic&rsquo;s commercial API terms, anything sent through the API, including your
              business details and project information, is not used to train their models. That&rsquo;s
              different from a free consumer AI chat tool, where inputs can be used for training unless
              you opt out. Nothing you submit here becomes training data for anyone.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-bold tracking-[0.2em] uppercase text-[#4B858E] mb-4">
              Encryption
            </h2>
            <p>
              All traffic to and from this site is encrypted in transit (HTTPS/TLS), enforced through
              Vercel and Cloudflare. Data at rest, including your account information, project data, and
              uploaded files, is stored on Supabase&rsquo;s AWS infrastructure, which encrypts data at
              rest by default.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-bold tracking-[0.2em] uppercase text-[#4B858E] mb-4">
              Your Files Stay Private
            </h2>
            <p>
              Files you upload to a project dashboard are stored in a private file bucket with no public
              URL. Every download link is generated on request, signed, and expires automatically. Files
              are always served as a forced download rather than opened directly in the browser, which
              closes off a common way a malicious file type could otherwise be used against you or
              anyone else viewing the project.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-bold tracking-[0.2em] uppercase text-[#4B858E] mb-4">
              Access Control
            </h2>
            <p>
              Project and client dashboards that aren&rsquo;t public are protected by their own password.
              Passwords are never stored in plain text, they&rsquo;re salted and hashed, and every check
              against them uses a comparison method built to resist timing-based attacks. Sessions are
              tracked with a signed token, not a guessable ID, so a session can&rsquo;t be forged by
              modifying a cookie. Admin access to the underlying systems is restricted to a single
              verified account.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-bold tracking-[0.2em] uppercase text-[#4B858E] mb-4">
              Built on Certified Infrastructure
            </h2>
            <p>
              World Shift Technologies is a lean, founder-led operation, and hasn&rsquo;t pursued its own
              SOC 2 certification. What that infrastructure runs on has: Vercel, Supabase, and
              Cloudflare, the three providers that actually touch your data, are each independently SOC 2
              Type II certified in their own right. You&rsquo;re not relying on my word alone that the
              hosting, database, and network layers are handled properly.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-bold tracking-[0.2em] uppercase text-[#4B858E] mb-4">
              What We Don&rsquo;t Do
            </h2>
            <p>
              We don&rsquo;t sell your data. We don&rsquo;t use it for advertising. We don&rsquo;t share
              it beyond the small set of vendors required to run the site and deliver the work, all of
              which are listed in the{" "}
              <Link href="/privacy" className="text-[#4B858E] hover:underline">
                Privacy Policy
              </Link>
              . Your project files and business information are used for exactly one purpose: doing the
              work you hired World Shift Technologies to do.
            </p>
          </section>

          <section>
            <h2 className="text-xs font-bold tracking-[0.2em] uppercase text-[#4B858E] mb-4">
              Data Retention & Deletion
            </h2>
            <p>
              Project data and files are retained for as long as your project or account is active. You
              can request deletion of your data at any time by emailing{" "}
              <a href="mailto:drew@worldshifttech.com" className="text-[#4B858E] hover:underline">
                drew@worldshifttech.com
              </a>
              . Full retention details, including guest submissions, are in the{" "}
              <Link href="/privacy" className="text-[#4B858E] hover:underline">
                Privacy Policy
              </Link>
              .
            </p>
          </section>

          <section>
            <h2 className="text-xs font-bold tracking-[0.2em] uppercase text-[#4B858E] mb-4">
              Report a Concern
            </h2>
            <p>
              If you find a security issue anywhere on this site or in how a project dashboard behaves,
              I want to know about it before anyone else does. Email{" "}
              <a href="mailto:drew@worldshifttech.com" className="text-[#4B858E] hover:underline">
                drew@worldshifttech.com
              </a>{" "}
              with what you found and I&rsquo;ll respond directly.
            </p>
          </section>

          <section>
            <p className="text-[#76777A] text-sm">
              This page is a plain-language summary. The legal terms governing data use and your rights
              are in the{" "}
              <Link href="/privacy" className="text-[#4B858E] hover:underline">
                Privacy Policy
              </Link>{" "}
              and{" "}
              <Link href="/terms" className="text-[#4B858E] hover:underline">
                Terms and Conditions
              </Link>
              .
            </p>
          </section>

        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-[#00205C]/[0.12] py-8 px-6">
        <div className="max-w-3xl mx-auto text-navy/70 text-sm">
          <p>&copy; {new Date().getFullYear()} World Shift Technologies</p>
        </div>
      </footer>

    </div>
  );
}
